# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [14]:
array_zeros = np.zeros(10)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [13]:
array_size = np.array([[1, 2, 3, 4]])
print(array_size.shape)

(1, 4)


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
array_fif = np.zeros(10)
array_fif[4] = 1
print(array_fif)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
array_arange = np.arange(10, 50)
print(array_arange)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
array_reverse = np.arange(10)
print(array_reverse)
print(array_reverse[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
array_matrix = np.arange(9).reshape(3, 3)
print(array_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [24]:
array_nonzero = np.nonzero([1, 2, 0, 0, 4, 0])
print(array_nonzero[0])

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [26]:
array_identity = np.eye(3)
print(array_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [27]:
array_random = np.random.random((3, 3, 3))
print(array_random)

[[[0.20815335 0.1844463  0.90166151]
  [0.53831278 0.86560736 0.26204144]
  [0.58910354 0.33862191 0.76112038]]

 [[0.74633751 0.37706419 0.45808877]
  [0.15454119 0.80984649 0.37075802]
  [0.43444101 0.01868983 0.70974417]]

 [[0.72159071 0.34438112 0.34375992]
  [0.60050586 0.76360599 0.87645433]
  [0.81418333 0.89250921 0.20789375]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [28]:
array_rd = np.random.random((10,10))
print(array_rd)
print(np.min(array_rd))
print(np.max(array_rd))

[[0.24238913 0.0338399  0.30408167 0.48280458 0.20650812 0.51187729
  0.42936732 0.09916843 0.86057107 0.31666996]
 [0.31423187 0.78656226 0.83083656 0.04658895 0.17596277 0.07374205
  0.31325187 0.57169064 0.54821746 0.98903396]
 [0.64220665 0.4584697  0.73541274 0.58696264 0.68442834 0.27560144
  0.12188397 0.97330364 0.60261578 0.22702964]
 [0.43460449 0.42633993 0.23049647 0.33023455 0.4526778  0.04804151
  0.64647758 0.26556725 0.73355814 0.79724222]
 [0.7647592  0.64246827 0.60133871 0.11127984 0.55688616 0.67925665
  0.41363324 0.57138179 0.68966172 0.44563752]
 [0.85824809 0.30470429 0.20283414 0.13269593 0.04023792 0.43342702
  0.16568061 0.46128717 0.17226212 0.06940309]
 [0.41652163 0.68001497 0.06243995 0.39712041 0.85299701 0.55696774
  0.87981984 0.08917165 0.76848126 0.87501771]
 [0.62091724 0.3349742  0.87894829 0.05737237 0.31679988 0.57344887
  0.20451092 0.15597689 0.64398135 0.41564148]
 [0.80950412 0.54567967 0.25327025 0.06885405 0.19057149 0.01960664
  0.44052822

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [29]:
array_rd1 = np.random.random(30)
print(array_rd1)
print(np.mean(array_rd1))

[0.11795464 0.333765   0.93539212 0.3761453  0.17065894 0.01764096
 0.21659345 0.90315108 0.04272978 0.78504161 0.26703368 0.35016184
 0.01943507 0.68236176 0.80206418 0.77004174 0.56654062 0.59916995
 0.7464387  0.44808089 0.08802747 0.9697403  0.48627413 0.11562298
 0.08936248 0.42055659 0.11074318 0.61383684 0.92235361 0.56870496]
0.4511874617184482


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [34]:
array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [33]:
array_diag = np.diag(1+np.arange(4), k=-1)
print(array_diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [35]:
array_checker = np.zeros((8, 8))
array_checker[1::2, ::2] = 1
array_checker[::2, 1::2] = 1
print(array_checker)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [32]:
array_index = np.unravel_index(100, (6, 7, 8))
print(array_index)

(1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [30]:
array_normal = np.random.random((5,5))
normal_mean = np.mean(array_normal)
normal_std = np.std(array_normal)
normal_array = (array_normal - normal_mean) / normal_std
print(normal_array)

[[ 1.02125319  1.31888137  0.95932602 -0.8174445  -0.56925027]
 [ 0.58557335 -1.07632094 -0.43240201 -0.061363   -0.6357443 ]
 [ 0.93729594  0.83974502 -1.30314598  1.11670302  1.17902229]
 [-0.09426051 -1.56605143 -1.31479477 -0.23218853  1.10841742]
 [-1.64669347  1.39524206 -0.46676941 -1.10000434  0.8549738 ]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [36]:
array_color = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
print(array_color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


### 21. Multiply a 5x3 matrix by a 3x2 matrix real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
