# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
array_zeros = np.zeros(10)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [3]:
array_size = np.array([[1, 2, 3, 4]])
print(array_size.nbytes)

32


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
array_fif = np.zeros(10)
array_fif[4] = 1
print(array_fif)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
array_arange = np.arange(10, 50)
print(array_arange)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
array_reverse = np.arange(10)
print(array_reverse)
print(array_reverse[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array_matrix = np.arange(9).reshape(3, 3)
print(array_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array_nonzero = np.nonzero([1, 2, 0, 0, 4, 0])
print(array_nonzero[0])

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
array_identity = np.eye(3)
print(array_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
array_random = np.random.random((3, 3, 3))
print(array_random)

[[[0.73108353 0.69683663 0.30967843]
  [0.66397509 0.16109094 0.5504114 ]
  [0.80451245 0.45190097 0.82605328]]

 [[0.41880587 0.32827525 0.53869253]
  [0.28425775 0.31385846 0.00943672]
  [0.04178194 0.31121367 0.08391922]]

 [[0.92984134 0.02803207 0.3579517 ]
  [0.92795942 0.81579446 0.22353147]
  [0.87395108 0.61799394 0.01742766]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
array_rd = np.random.random((10,10))
print(array_rd)
print(np.min(array_rd))
print(np.max(array_rd))

[[0.78001923 0.75522559 0.33869616 0.72230882 0.02860515 0.52742418
  0.99114024 0.42615696 0.83043354 0.39878104]
 [0.97987709 0.84303948 0.32456626 0.80371443 0.730465   0.57660086
  0.29127049 0.32045456 0.38444667 0.3548309 ]
 [0.14863185 0.44064549 0.44157548 0.62381806 0.75971756 0.43754352
  0.4870997  0.19719163 0.40594719 0.19626416]
 [0.76383308 0.7124854  0.48248186 0.82226206 0.53618828 0.02574962
  0.98312903 0.32260726 0.68038862 0.67138078]
 [0.93715579 0.33138928 0.75602263 0.0270297  0.93694564 0.81888019
  0.60518966 0.66690419 0.6170833  0.65253167]
 [0.12528471 0.07368051 0.6070521  0.54710964 0.98696436 0.3175184
  0.22692312 0.32464504 0.11170142 0.91306056]
 [0.00635988 0.14400248 0.25271906 0.6077268  0.20243468 0.93113553
  0.44812592 0.62442691 0.07598997 0.33890948]
 [0.99785383 0.91381678 0.38026186 0.40383417 0.82902824 0.75009272
  0.5602861  0.21391381 0.11791632 0.29316734]
 [0.33032956 0.52561512 0.91467968 0.68210507 0.95406756 0.16594753
  0.81554039 

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
array_rd1 = np.random.random(30)
print(array_rd1)
print(np.mean(array_rd1))

[0.40632218 0.71566563 0.1968575  0.68342005 0.78430316 0.91772717
 0.71220449 0.78809763 0.49554811 0.74706651 0.39258765 0.16016713
 0.28525109 0.07081027 0.78434569 0.87944131 0.9946957  0.80240847
 0.29960087 0.42040252 0.33243855 0.02972723 0.81938462 0.71994802
 0.80420567 0.49881099 0.00426501 0.12866459 0.18900678 0.27861337]
0.511399598711581


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

어떤 수를 nan과 곱하면 결과는 항상 nan이 나옴

nan은 자기 자신과도 같지 않음 (False)

nan은 비교 연산을 수행하면 False를 반환함

nan에 더하기, 빼기 등의 연산을 진행하면 결과 nan이 나옴

set에 nan이 들어있어도 nan 자체의 비교연산은 항상 False이므로 in 연산자의 경우 True를 반환함

python에서는 부동소수점 오차를 허용하기 때문에 True를 반환함

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
array_diag = np.diag(1+np.arange(4), k=-1)
print(array_diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
array_checker = np.zeros((8, 8))
array_checker[1::2, ::2] = 1
array_checker[::2, 1::2] = 1
print(array_checker)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [57]:
array_index = np.unravel_index(99, (6, 7, 8))
print(array_index)

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
array_normal = np.random.random((5,5))
normal_mean = np.mean(array_normal)
normal_std = np.std(array_normal)
normal_array = (array_normal - normal_mean) / normal_std
print(normal_array)

[[ 0.1049357   0.58533445 -0.36353653 -0.9418902  -1.70412462]
 [ 0.37363119  0.02343051  0.44496056 -0.53593471  1.36656982]
 [-0.6014283   1.64518472  0.08122866 -1.54656574 -1.17288892]
 [-1.70756381  0.70892521  1.2433606   1.07775693 -1.34848199]
 [ 0.06667774  0.96610415  1.53866365  0.06206219 -0.36641126]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
array_color = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
print(array_color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


### 21. Multiply a 5x3 matrix by a 3x2 matrix real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
