#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) **발표**

In [9]:
import numpy as np

arr1 = np.random.random((5,3)) # array1에 5*3 matrix 생성
arr2 = np.random.random((3,2)) # array2에 3*2 matrix 생성
print(arr1)
print(arr2)
print(np.dot(arr1, arr2)) # 행렬 내적 출력

[[0.46411623 0.46233022 0.2124173 ]
 [0.00360894 0.16482671 0.58744552]
 [0.81259026 0.04175769 0.32930718]
 [0.54812211 0.63129481 0.77321279]
 [0.03515254 0.22930642 0.81263661]]
[[0.91657408 0.62020288]
 [0.48266032 0.46060777]
 [0.81481625 0.52389694]]
[[0.82162643 0.61208389]
 [0.56152332 0.38591965]
 [1.03327879 0.69572776]
 [1.43712182 1.03581002]
 [0.80504653 0.55315986]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) **발표**

In [10]:
import numpy as np

arr22=np.arange(10) # 1차원 배열 생성
arr22[(arr22>3) & (arr22<8)] *= -1 # arr22 배열의 3 초과 8 미만의 값에 -1을 곱하여 부호를 바꿈
print(arr22)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [1]:
# Author: Jake VanderPlas

print(sum(range(5),-1)) # -1부터 시작하여 range(5)에 해당하는 0부터 4까지의 값을 더함
from numpy import *
print(sum(range(5),-1)) # 축이 -1인 1차원 배열의 합이므로 0부터 4까지 더한 합을 출력함

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [12]:
Z = np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

1번: 거듭제곱

2번: 비트 시프트연산자

3번: 존재하지 않는 연산자 (불가능, R에서 사용됨)

4번: 복소수 연산자

5번: 나누기 연산

6번: 잘못된 비교연산 (python에서는 가능하나, numpy에서는 지원되지 않는 연산자)


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-64-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-64-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-64-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

0/0은 수학적으로 지원되지 않는 연산 -> nan을 반환함

0//0은 정수 나눗셈으로 마찬가지로 정의되지 않음 -> ZeroDivisionError 반환

nan을 int 타입으로 나타내면 시스템 최소값으로 변하고 이후 float으로 타입을 변환하면 매우 작은 음수로 변하게 됨


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.unique(Z1[np.isin(Z1,Z2)]))

[4 1 3 2 4 6 0 9 7 9]
[4 1 1 7 3 8 7 9 9 3]
[1 3 4 7 9]


In [14]:
import numpy as np

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

arr_intersect = np.intersect1d(Z1, Z2)
print(Z1, Z2)
print(arr_intersect)

[3 2 0 8 3 7 1 8 7 6] [9 1 3 2 8 2 7 2 0 2]
[0 1 2 3 7 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False

: emath를사용하면 복소수 연산이 가능하지만 np.sqrt(-1)는 연산이 불가능하기 때문에 둘의 연산은 다름

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-67-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆) **발표**
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [24]:
A = np.random.randint(10, size=1)
B = np.random.randint(10, size=1)
print(A, B)
np.add(A, B, out=B)
np.negative(A, out=A)
np.divide(A,2)
print(np.multiply(B, A))

[8] [2]
[-80]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [30]:
arr30 = np.random.uniform(0, 10, 5)
print(arr30)
print(arr30 // 1) # //의 사용 (//: 몫의 연산자)
print(arr30 - (arr30 % 1)) # %의 사용 (%: 나머지 연산자)

[5.58338553 4.86037846 8.00459004 1.32895199 0.0657255 ]
[5. 4. 8. 1. 0.]
[5. 4. 8. 1. 0.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [31]:
arr31 = np.random.randint(0,5,25).reshape((5,5))
print(arr31)

[[4 3 4 0 0]
 [2 4 2 4 3]
 [2 3 3 0 2]
 [4 0 2 2 2]
 [2 4 3 2 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [32]:
arr32 = np.random.randint(0, 10, 10)
print(arr32)
print(np.sort(arr32)) # np.sort()함수를 이용하여 sort 진행

[0 8 0 4 6 8 2 8 5 3]
[0 0 2 3 4 5 6 8 8 8]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(np.array_equal(A,B)) # 부동소수점까지 같아야 True가 도출됨

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [37]:
import numpy as np

arr34 = np.random.random((10,2))
x, y = arr34[:,0], arr34[:,1] # x에는 x축 값을, y에는 y축 값을 넣음
r= np.sqrt(x ** 2 + y ** 2) # 거리를 계산함
theta = np.arctan2(y, x) # 각도를 계산함
print(r,theta) # 극좌표로 나타냄

[0.14631294 0.99152187 0.98683422 0.7480591  1.20900649 0.48717644
 1.02498872 0.50936754 0.82855267 0.61415037] [1.01507209 1.34147053 0.6890773  0.37403119 0.79442513 1.12554932
 0.92092516 0.51591687 1.38862425 1.02892922]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [38]:
Z = np.random.randint(0,10,10)
Z[Z.argmax()] = 0
print(Z)

[6 0 9 8 2 8 0 7 5 5]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [39]:
Z = np.arange(100)
v = np.random.uniform(0,100)
distance=np.abs(Z-v) # Z와 v 간의 거리 계산

closest_index=np.argmin(distance) # 가장 가까운 값의 인덱스를 찾음
Z[closest_index]

29

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [53]:
import numpy as np

Z = np.arange(9).reshape(3,3)

# ndenumerate 사용
print("ndenumerate 사용")
for index, value in np.ndenumerate(Z):
  print(index, value)

# ndindex 사용
print("ndindex 사용")
np.ndindex(Z.shape)
for index in np.ndindex(Z.shape):
  print(index, Z[index])


ndenumerate 사용
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
ndindex 사용
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [42]:
n = 5
p = 4
arr38 = np.zeros((n,n))
np.put(arr38, np.random.choice(range(n*n), p, replace = False),8)
print(arr38)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 8.]
 [8. 0. 0. 8. 0.]
 [0. 0. 8. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [43]:
# column 1로 정렬
col1 = np.random.randint(0,10,(3,3))
print(col1)
col1[np.argsort(col1[:,0])]

[[6 4 4]
 [2 5 4]
 [1 1 9]]


array([[1, 1, 9],
       [2, 5, 4],
       [6, 4, 4]])

In [45]:
# column 2로 정렬
col2 = np.random.randint(0,10,(3,3))
print(col2)
col2[np.argsort(col2[:,1])]

[[0 3 8]
 [0 6 7]
 [3 4 7]]


array([[0, 3, 8],
       [3, 4, 7],
       [0, 6, 7]])

In [48]:
# column 3로 정렬
col3 = np.random.randint(0,10,(3,3))
print(col3)
col3[np.argsort(col3[:,2])]

[[3 6 4]
 [8 3 2]
 [8 2 1]]


array([[8, 2, 1],
       [8, 3, 2],
       [3, 6, 4]])